# Generated by Django 5.2.8 on 2025-11-18 14:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('duracao_horas', models.IntegerField()),
                ('nivel', models.CharField(max_length=50)),
                ('conteudo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50)),
                ('pronomes', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('pcd', models.BooleanField(default=False)),
                ('habilidades', models.TextField(blank=True, help_text='Habilidades separadas por vírgula')),
                ('experiencia_anos', models.IntegerField(default=0)),
                ('escolaridade', models.CharField(blank=True, max_length=100)),
                ('area_interesse', models.CharField(blank=True, max_length=200)),
                ('pretensao_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('curriculo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField(help_text='Requisitos da vaga')),
                ('habilidades_necessarias', models.TextField(help_text='Habilidades separadas por vírgula')),
                ('nivel', models.CharField(choices=[('estagio', 'Estágio'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior')], max_length=20)),
                ('tipo', models.CharField(choices=[('remoto', 'Remoto'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], max_length=20)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experiencia_minima', models.IntegerField(default=0, help_text='Anos de experiência')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('pausada', 'Pausada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Vagas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('concluido', models.BooleanField(default=False)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_progresso', to='core.candidato')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
            options={
                'verbose_name_plural': 'Progressos de Cursos',
                'unique_together': {('candidato', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score de compatibilidade (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado'), ('entrevista', 'Em Entrevista'), ('contratado', 'Contratado')], default='pendente', max_length=20)),
                ('candidato_interessado', models.BooleanField(default=False)),
                ('empresa_interessada', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.vaga')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-score', '-criado_em'],
                'unique_together': {('candidato', 'vaga')},
            },
        ),
    ]
