# Generated by Django 5.2.8 on 2025-11-19 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('match', 'Novo Match'), ('mensagem', 'Nova Mensagem'), ('vaga', 'Nova Vaga'), ('candidatura', 'Nova Candidatura'), ('sistema', 'Notificação do Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, help_text='URL para redirecionar ao clicar', max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
