# Generated by Django 5.2.8 on 2025-11-19 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Match relacionado à conversa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.match'),
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('entrevista_agendada', 'Entrevista Agendada'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='pendente', max_length=30)),
                ('carta_apresentacao', models.TextField(blank=True, help_text='Carta de apresentação do candidato')),
                ('observacoes_empresa', models.TextField(blank=True, help_text='Observações da empresa sobre a candidatura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.candidato')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatura', to='core.match')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.vaga')),
            ],
            options={
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-criado_em'],
                'unique_together': {('candidato', 'vaga')},
            },
        ),
    ]
